# The URL the site will be built for
base_url = "https://headless-voyager.vercel.app"
title = "headlessvoyager"

theme = "apollo"
generate_feeds = true
taxonomies = [{ name = "tags" }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"

[extra]
# Put all your custom variables here
site_title = "headless voyager"

favicon = true

socials = [
  # { name = "github", url = "https://github.com/headless-voyager", icon = "github" },
  # { name = "email", url = "mailto:vikram.v.email@gmail.com", icon = "email" },
  # { name = "linkedin", url = "https://www.linkedin.com/in/vikramvenkataramanan", icon = "linkedin" },
  { name = "rss", url = "/atom.xml", icon = "rss" },
]

menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/about", url = "/about", weight = 2 },
  # { name = "/tags", url = "/tags", weight = 3 },
]
