allowBuilds:
  puppeteer: true
minimumReleaseAgeExclude:
  - pa11y-ci@5.0.0
overrides:
  basic-ftp@<=6.2.0: ^6.2.1
  lighthouse: 13.5.0
  proxy-agent: ^8.0.1
  tmp@<0.2.6: ^0.2.6
  tmp@<=0.2.3: ^0.2.4
  uuid@<11.1.1: ^11.1.1
