name: Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.23.4

      - run: zola build
